services:
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

networks:
  inception:
    name: inception

volumes:
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seongjko/data/wordpress
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seongjko/data/mariadb