version: '3'

# docker-compose에서 실행할 컨테이너들을 정의하는 섹션
services:
  mariadb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - wp_data:/var/www/html
    ports:
      - "443:443"
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seongjko/data/wordpress
      # device: /Users/goseongjun/data/wordpress
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/seongjko/data/mariadb
      # device: /Users/goseongjun/data/mariadb

networks:
  inception:
    driver: bridge
